version: '3.8'

services:
  # MySQL Database Service
  database:
    image: mysql:8.0
    container_name: attendance_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: attendance_system
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: attendance_user
      MYSQL_PASSWORD: attendance_pass
    volumes:
      - db_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    ports:
      - "3306:3306"
    networks:
      - attendance_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # PHP Application Service - Using pre-built image
  web:
    image: php:8.1-apache
    container_name: attendance_web
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - attendance_network
    environment:
      - DB_HOST=database
      - DB_NAME=attendance_system
      - DB_USER=attendance_user
      - DB_PASS=attendance_pass
    volumes:
      - ./web:/var/www/html
    command: >
      bash -c "
      docker-php-ext-install pdo_mysql &&
      a2enmod rewrite &&
      chown -R www-data:www-data /var/www/html &&
      apache2-foreground
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"] 
      interval: 30s
      timeout: 10s
      retries: 3

  # phpMyAdmin (optional - for database management)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: attendance_phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_HOST=database
      - PMA_USER=attendance_user
      - PMA_PASSWORD=attendance_pass
      - MYSQL_ROOT_PASSWORD=rootpassword
    ports:
      - "8081:80"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - attendance_network

networks:
  attendance_network:
    driver: bridge

volumes:
  db_data:
    driver: local